package com.manulife.pension.service.loan;

public enum LoanErrorCode {

	// LRA.12, LRA.22
	LRK01_IS_OFF,

	// LRA.13, LRA.23
	ALLOW_ONLINE_LOANS_IS_OFF,

	// LRA.14, LRA.25
	PARTICIPANT_CURRENT_ACCOUNT_BALANCE_IS_ZERO,

	// LRA.15, LRA.28
	PARTICIPANT_STATUS_IS_NOT_ACTIVE,

	// LRA.16, LRA.30
	PARTICIPANT_HAS_POSITIVE_PBA_BALANCE,

	// LRA.17, LRA.31
	PARTICIPANT_NUMBER_OF_LOANS_EXCEEDED,

	// LRA.18
	PARTICIPANT_DRAFT_LOAN_REQUEST_EXISTS,

	// LRA.19, LRA.26
	PARTICIPANT_HAS_PENDING_LOAN_REQUEST,

	// LRA.20, LRA.33
	FORWARD_UNREVERSED_LOAN_TRANSACTION_EXISTS,

	// LRA.24
	PARTICIPANT_HAS_GIFL_FOR_PARTICIPANT_INITIATED,

	// LRA.668
    PARTICIPANT_HAS_GIFL_FOR_EXTERNAL_USER_INITIATED,
    
    // LRA.697
    MONEY_TYPE_IS_NO_LONGER_A_CONTRACT_MONEY_TYPE,

	// LRA.27
	PARTICIPANT_HAS_WITHDRAWAL_REQUEST,

	// LRA.29
	CONTRACT_STATUS_NOT_ACTIVE_NOR_FROZEN,

	// LRA.32
	LOAN_ABOUT_TO_EXPIRE,

	// LRA.34
	VESTING_CREDITING_METHOD_IS_UNSPECIFIED,

	// LRA.35
	VESTING_SCHEDULE_HAS_NOT_BEEN_SET_UP,

	// LRA.36
	VESTING_MISSING_EMPLOYEE_DATA,

	// LRA.37
	VESTING_MORE_RECENT_DATA_USED_FOR_CALCULATION_CODE,

	// LRA.38
	VESTING_SERVICE_OTHER_NON_CRITICAL_ERROR,

	// LRA.39
	VESTING_SERVICE_CRITICAL_ERROR,

	// LRA.40
	REQUESTED_AMOUNT_EXCEEDS_AVAILABLE_AMOUNT,

	// LRA.536
	CONTRACT_STATUS_IS_FROZEN_FOR_APPROVAL,

	// LRA.537
	PARTICIPANT_STATUS_IS_NOT_ACTIVE_FOR_APPROVAL,

	MISSING_LEGALLY_MARRIED_IND,

	MISSING_LOAN_TYPE,

	LOAN_REASON_TOO_LONG,

	LOAN_REASON_INVALID_CHARACTER,

	MUST_ENTER_NOTE_TO_PARTICIPANT_ON_DENY,

	NOTE_TO_PARTICIPANT_TOO_LONG,

	NOTE_TO_ADMINISTRATOR_TOO_LONG,
	
	NOTE_TO_PARTICIPANT_INVALID_CHARACTERS,
	
	NOTE_TO_ADMINISTRATOR_INVALID_CHARACTERS,

	MUST_ENTER_LOAN_REASON,

	MISSING_EXPIRATION_DATE,

	EXPIRATION_DATE_LESS_THAN_MININUM_ALLOWED,

	EXPIRATION_DATE_GREATER_THAN_MAXIMUM_ALLOWED,

	EXPIRATION_DATE_INVALID_FORMAT,

	EXPIRATION_DATE_INVALID_VALUE,

	PAYROLL_DATE_LESS_THAN_EQUAL_TO_ESTIMATED_LOAN_START_DATE,

	MISSING_PAYROLL_DATE,

	PAYROLL_DATE_LESS_THAN_MININUM_ALLOWED,
	
    PAYROLL_DATE_GREATER_THAN_MAXIMUM_ALLOWED,

	PAYROLL_DATE_LESS_THAN_EQUAL_TO_NEXT_BUSINESS_DATE,

	PAYROLL_DATE_INVALID_FOR_SEMI_MONTHLY_PAYMENT_FREQUENCY,
	
	PAYROLL_DATE_INVALID_FORMAT,

	PAYROLL_DATE_INVALID_VALUE,

	DEFAULT_PROVISION_TOO_LONG,

	DEFAULT_PROVISION_INVALID_CHARACTER,

	MISSING_DEFAULT_PROVISION,

	MAXIMUM_LOAN_BALANCE_IN_LAST_12_MONTHS_NON_NUMERIC,

	MAXIMUM_LOAN_BALANCE_IN_LAST_12_MONTHS_TOO_LOW,

	MAXIMUM_LOAN_BALANCE_IN_LAST_12_MONTHS_INVALID_FORMAT,

	OUTSTANDING_LOANS_COUNT_NON_NUMERIC,

	OUTSTANDING_LOANS_COUNT_TOO_HIGH,

	OUTSTANDING_LOANS_COUNT_TOO_LOW,

	CURRENT_OUTSTANDING_LOAN_BALANCE_NON_NUMERIC,

	CURRENT_OUTSTANDING_LOAN_BALANCE_INVALID_FORMAT,

	CURRENT_OUTSTANDING_LOAN_BALANCE_TOO_LOW,

	TPA_LOAN_ISSUE_FEE_NON_NUMERIC,

	TPA_LOAN_ISSUE_FEE_INVALID_FORMAT,

	TPA_LOAN_ISSUE_FEE_EXCEEDS_MAXIMUM,

	TPA_LOAN_ISSUE_FEE_MAY_BE_PAYABLE_BY_PARTICIPANT,

	VESTING_PERCENTAGE_NON_NUMERIC,

	VESTING_PERCENTAGE_INVALID_FORMAT,

	VESTING_PERCENTAGE_TOO_HIGH,

	// LRA.233
	LOAN_AMOUNT_BLANK_OR_NON_NUMERIC,

	LOAN_AMOUNT_INVALID_FORMAT,

	// LRA.235
	LOAN_AMOUNT_LESS_THAN_MINIMUM,

	// LRA.237
	LOAN_AMOUNT_GREATER_THAN_MAXIMUM,

	// LRA.247
	AMORTIZATION_MONTHS_IS_ZERO,

    AMORTIZATION_PERIOD_TOO_HIGH,

	// LRA.270
	PAYMENT_FREQUENCY_IS_EMPTY,

	// LRA.271
	PAYMENT_FREQUENCY_NOT_MATCHING_PLAN_VALUE,

	// LRA.280
	INTEREST_RATE_BLANK_OR_NON_NUMERIC,

	INTEREST_RATE_INVALID_FORMAT,

    INTEREST_RATE_OUT_OF_RANGE,

    // LRA.329, 330
	ADDRESS_LINE1_INVALID_CHARACTER,
	
	// LRA.331
	ADDRESS_LINE1_REQUIRED,
	
	// LRA.338, 339
	ADDRESS_LINE2_INVALID_CHARACTER,

	// LRA.347, 348
	CITY_INVALID_CHARACTER,
	
	// LRA.349
	CITY_REQUIRED,

	// LRA.363, 364
	STATE_INVALID_CHARACTER,
	
	// LRA.365
	STATE_REQUIRED,
	
	// LRA.374
	COUNTRY_REQUIRED,

	// LRA.382
	ZIP_CODE_INVALID_US_FORMAT,
	
	// LRA.383
	ZIP_CODE_INVALID_RANGE,
	
	// LRA.384
	ZIP_CODE_REQUIRED,
	
	// LRA.401, 402
	ZIP_CODE_INVALID_CHARACTER,
	
	// LRA.410
	ABA_ROUTING_NUMBER_NON_NUMERIC,
	
	// LRA.421
	ACCOUNT_NUMBER_INVALID_CHARACTER,
	
	// LRA.422
	ACCOUNT_NUMBER_REQUIRED,

	// LRA.429
	ACCOUNT_TYPE_REQUIRED,

	// LRA.416
	BANK_NAME_REQUIRED,
	
	TRUTH_IN_LENDING_NOTICE_NOT_ACCEPTED,
	
	PROMISSORY_NOTE_NOT_ACCEPTED,
	
	AT_RISK_TRANSACTION_NOT_ACCEPTED,
	
	CONCURRENT_UPDATE_DETECTED,
	
	LOAN_ISSUE_FEE_GREATER_THAN_PLAN_MINIMUM,
	
	LIA_ENABLED_FOR_PARTICIPANT,
	
	//LRA.734
	PARTICIPANT_HAS_INSTALLMENT_WITHDRAWAL
	;
}
