package com.manulife.pension.service.loan.util;

public interface LoanContentConstants {

	int TRUTH_IN_LENDING_NOTICE_HTML = 60573;
	
	int TRUTH_IN_LENDING_NOTICE_PDF = 60044;
	
	int PROMISSORYNOTE_AND_IRREVOCABLEPLEDGE_HTML = 60572;

	int PROMISSORYNOTE_AND_IRREVOCABLEPLEDGE_PDF = 60045;
	
	int AT_RISK_TRANSACTION_HTML = 60316;
	
	int AT_RISK_EMAIL_TRANSACTION_HTML = 72612;

	int AMORTIZATION_SCHEDULE_HTML = 60335;
	
	int AMORTIZATION_SCHEDULE_PDF = 60048;
	
	int LOAN_FORM_PDF = 60334;

	int DEFAULT_PROVISION = 60087;
	
	int PARTICIPANT_AUTHORIZATION = 60094;
	
	int LOAN_PACKAGE_INSTRUCTIONS_FOR_PARTICIPANT = 60332;
	
	int LOAN_PACKAGE_INSTRUCTIONS_FOR_ADMIN = 60333;
	
	int LOAN_INSTRUCTIONS = 60046;
}
