package com.manulife.pension.ps.web.onlineloans;

import com.manulife.pension.service.loan.LoanErrorCode;

public interface LoanContentConstants {

	int LOAN_DELETED = 1256; // Message code
	
	int LOAN_EXPIRED = 1257; // Message code
	
    int PAGE_CONTENT_NOT_FINAL_DISCLAIMER = 60108;
    
    int GIFL_MSG_EXTERNAL_USER_INITIATED = 2702;

    int GIFL_MSG_PARTICIPANT_INITIATED = 2616;

	int MSG_PARTICIPANT_ACCOUNT_BALANCE_IS_ZERO = 2409;

	int SPOUSAL_CONSENT_MAY_BE_REQUIRED = 60398;

	int SPOUSAL_CONSENT_MAY_BE_REQUIRED_IF_MARRIED = 60401;

	int SPOUSAL_CONSENT_MUST_BE_OBTAINED = 60400;

	int SPOUSAL_CONSENT_IS_NOT_REQUIRED = 60399;

    int NOTE_TO_PARTICIPANT_PRINT_CONTENT = 60098;

    int VIEW_NOTES_SECTION_FOOTER = 60097;

    int EMPLOYEE_SNAPSHOT_LINK = 55724;

	int PARTICIPANT_INFORMATION_SECTION_TITLE = 55721;

	int PARTICIPANT_INFORMATION_SECTION_FOOTER = 60086;

	int LOAN_DETAILS_SECTION_TITLE = 55723;

	int LOAN_REASON_TOO_LONG = 2701; // Message code

	int LOAN_REASON_INVALID_CHARACTER = 2625; // Message code

	int TPA_LOAN_ISSUE_FEE_NON_NUMERIC = 2635; // Message code

	int LOAN_CACULATIONS_TITLE = 60102;

	int AMORTIZATION_PERIOD_TOO_HIGH = 2659; // Message code

	int LOAN_AMOUNT_BLANK_OR_NON_NUMERIC = 2654; // Message code

	int LOAN_AMOUNT_INVALID_FORMAT = 1259; // Message code

	int LOAN_AMOUNT_LESS_THAN_MINIMUM = 2655; // Message code

	int LOAN_AMOUNT_GREATER_THAN_MAXIMUM = 2656; // Message code

	int PAYMENT_FREQUENCY_IS_EMPTY = 2660; // Message code

	int INTEREST_RATE_BLANK_OR_NON_NUMERIC = 2662; // Message code 

	int INTEREST_RATE_INVALID_FORMAT = 2663;   // Message code

	int INTEREST_RATE_OUT_OF_RANGE = 1260; // Message code
	
	int DEFAULT_PROVISION_EXPLANATION = 60720;

	int DEFAULT_PROVISION_TOO_LONG = 2638; // Message code

	int DEFAULT_PROVISION_INVALID_CHARACTER = 2639; // Message code

	int CACULATE_MAX_AVAILABLE_FOR_LOAN_SECTION_TITLE = 60101;

	int VESTING_EXPLANATION_LINK = 55738;

	int VESTING_PERCENTAGE_NON_NUMERIC = 2641; // Message code

	int VESTING_PERCENTAGE_INVALID_FORMAT = 2642; // Message code

	int VESTING_PERCENTAGE_TOO_HIGH = 2643; // Message code

	int MAXIMUM_LOAN_BALANCE_IN_LAST_12_MONTHS_NON_NUMERIC = 2644; // Message
																	// code

	int MAXIMUM_LOAN_BALANCE_IN_LAST_12_MONTHS_TOO_LOW = 2646; // Message code

	int MAXIMUM_LOAN_BALANCE_IN_LAST_12_MONTHS_INVALID_FORMAT = 2645; // Message
																		// code

	int OUTSTANDING_LOANS_COUNT_NON_NUMERIC = 2647; // Message code

	int OUTSTANDING_LOANS_COUNT_TOO_LOW = 2648; // Message code

	int OUTSTANDING_LOANS_COUNT_TOO_HIGH = 2649; // Message code

	int CURRENT_OUTSTANDING_LOAN_BALANCE_NON_NUMERIC = 2650; // Message code

	int CURRENT_OUTSTANDING_LOAN_BALANCE_INVALID_FORMAT = 2651; // Message code

	int CURRENT_OUTSTANDING_LOAN_BALANCE_TOO_LOW = 2652; // Message code

	int CACULATE_MAX_LOAN_AVAILABLE_SECTION_FOOTER = 60089;

	int PAYMENT_INSTRUCTIONS_SECTION_TITLE = 55731;

	int WIRE_CHARGES_CONTENT = 60091;

	int ADDRESS_LINE1_INVALID_CHARACTER = 2664; // Message code

	int ADDRESS_LINE2_INVALID_CHARACTER = 2666; // Message code

	int CITY_INVALID_CHARACTER = 2667; // Message code

	int STATE_INVALID_CHARACTER = 2669; // Message code

	int ZIP_CODE_INVALID_CHARACTER = 2675; // Message code

	int ZIP_CODE_INVALID_US_FORMAT = 2672; // Message code

	int ABA_ROUTING_NUMBER_NON_NUMERIC = 2676; // Message code

	int BANK_LOOKUP_LINK = 60092;

	int ACCOUNT_NUMBER_INVALID_CHARACTER = 2678; // Message code

	int PAYMENT_INSTRUCTIONS_FOOTER = 60093;
	
    int NOTE_TO_PARTICIPANT_TOO_LONG = 2684;
    
    int NOTE_TO_ADMINISTRATOR_TOO_LONG = 2687;
    
    int NOTE_TO_PARTICIPANT_INVALID_CHARACTERS = 2685;
    
    int NOTE_TO_ADMINISTRATOR_INVALID_CHARACTERS= 2688;

	int DECLARATIONS_SECTION_TITLE = 55736;

	int AT_RISK_TRANSACTION_MESSAGE_CONTENT_KEY = 60316;
	int AT_RISK_TRANSACTION_MESSAGE_CONTENT_ID = 60316;

	int TRUTH_IN_LENDING_NOTICE_DISCLAIMER = 61035;

	int PROMISSORY_NOTE_DISCLAIMER = 61036;

	int DECLARATIONS_SECTION_FOOTER = 60095;

	int INVALID_DATE_FORMAT = 2627; // Message code

	int INVALID_MONTH_DAY_YEAR = 2628; // Message code

	int BUTTON_HELP_TEXT_EXIT_EDIT_MODE = 55726;

    int BUTTON_HELP_TEXT_EXIT_VIEW_MODE = 61842;

    int BUTTON_HELP_TEXT_DELETE = 56498;

	int BUTTON_HELP_TEXT_SAVE_AND_EXIT = 55728;

	int LINK_HELP_TEXT_LOAN_PACKAGE = 60318;

	int BUTTON_HELP_TEXT_LOAN_PACKAGE = 60965;
	
	int BUTTON_HELP_TEXT_PRINT_LOAN_REVIEW = 82454;

	int BUTTON_HELP_TEXT_DENY = 56499;

	int BUTTON_HELP_TEXT_SEND_FOR_REVIEW = 55747;

	int BUTTON_HELP_TEXT_SEND_FOR_ACCEPTANCE = 60321;

	int BUTTON_HELP_TEXT_SEND_FOR_APPROVAL = 55748;

	int BUTTON_HELP_TEXT_APPROVE = 55749;

    int BUTTON_FOOTER_EDIT_MODE = 60099;

    int BUTTON_FOOTER_VIEW_MODE = 60964;

    int LOAN_PACKAGE_DIALOG_TEXT = 60320;
    
    int LOAN_PACKAGE_NO_LONGER_VALID_TEXT = 61196;

	int APPROVAL_DIALOG_TEXT = 60322;

	int APPROVAL_DIALOG_PRT_INITIATED_SPOUSAL_CONSENT_REQD_IS_YES = 60323;

	int APPROVAL_DIALOG_PRT_INITIATED_SPOUSAL_CONSENT_REQD_IS_NO = 60324;

	int APPROVAL_DIALOG_PRT_INITIATED_SPOUSAL_CONSENT_REQD_IS_NULL = 60325;

	int APPROVAL_DIALOG_EXT_INITIATED_SPOUSAL_CONSENT_REQD_IS_YES = 60326;

	int APPROVAL_DIALOG_EXT_INITIATED_SPOUSAL_CONSENT_REQD_IS_NO = 60327;

	int APPROVAL_DIALOG_EXT_INITIATED_SPOUSAL_CONSENT_REQD_IS_NULL = 60328;

	int YOU_ARE_AT_TEXT_NEW_OR_DRAFT = 60104;

	int YOU_ARE_AT_TEXT_PENDING_REVIEW_PRT_INITIATED = 60105;

	int YOU_ARE_AT_TEXT_PENDING_REVIEW_EXT_USER_INITIATED = 60397;

	int YOU_ARE_AT_TEXT_PENDING_APPROVAL_PRT_INITIATED = 60107;

	int YOU_ARE_AT_TEXT_PENDING_APPROVAL_EXT_USER_INITIATED = 60106;

	int PRINT_LOAN_DOCUMENTS_DIALOG_TEXT = 60646;

	int SECTION_TITLE_BANK_INFORMATION = 60103;

	int BANK_DIALOG_FOOTER = 60100;

	int BANK_LOOKUP_NO_DATA_FOUND = 60329;

	int BANK_LOOKUP_MORE_THAN_ONE_ENTRY_FOUND = 60330;

	int BANK_LOOKUP_BANK_SELECTION_REQUIRED = 2692;
	
	int BANK_LOOKUP_BANK_NAME_REQUIRED = 2693;
	
	int BANK_LOOKUP_BANK_NAME_INVALID_CHARACTER = 2691;
	
	int ACCOUNT_BALANCE_FOOTNOTE_EXCLUDES_OUTSTANDING_LOAN_BALANCES = 60402;

	int ACCOUNT_BALANCE_FOOTNOTE_AT_TIME_REQUEST_REVIEWED = 60710;
	
	int LOAN_TYPE_DISABLED_TEXT = 95271;
}

