
C:\WINDOWS\system32\iisweb.vbs /delete "EZK US"
C:\WINDOWS\system32\iisweb.vbs /delete "EZK NY"
C:\WINDOWS\system32\iisweb.vbs /delete "EZK CMA"
C:\WINDOWS\system32\iisweb.vbs /delete "SupportCentral"
C:\WINDOWS\system32\iisweb.vbs /delete "PlanSponsor USA"
C:\WINDOWS\system32\iisweb.vbs /delete "PlanSponsor NY"
C:\WINDOWS\system32\iisweb.vbs /delete "PlanSponsor CMA"
C:\WINDOWS\system32\iisweb.vbs /delete "BrokerDealer"
C:\WINDOWS\system32\iisweb.vbs /delete "BD US"
C:\WINDOWS\system32\iisweb.vbs /delete "BD NY"
C:\WINDOWS\system32\iisweb.vbs /delete "BD CMA"
C:\WINDOWS\system32\iisweb.vbs /delete "Online Order"
C:\WINDOWS\system32\iisweb.vbs /delete "ACR"
