package com.manulife.pension.ps.web.investment.util;

/**
 * To hold all CMA keys and footnotes.
 * 
 * @author akarave
 *
 */
public class Constants {
	
	public enum Location {US, NY}
	
	public static final String FORMAT_TWO_DECIMALS = "0.00";
	public static final String ZERO = "0";
	public static final String NOT_APPLICABLE = "N/A";
	public static final int SCLALE = 2;
	
	public static final String FOOTNOTE_N1_TEXT = "N1";
	public static final String FOOTNOTE_N2_TEXT = "N2";
	public static final String FOOTNOTE_N7_TEXT = "N7";
	public static final String FOOTNOTE_N10_TEXT = "N10";
	public static final String FOOTNOTE_N11_TEXT = "N11";
	public static final String FOOTNOTE_N25_TEXT = "N25";
	
	public enum CmaKeys 
	{    

		/** CMA keys  **/
		
		RECORD_KEEPING_SUMMARY_INTRODUCTION(84930),
		RECORD_KEEPING_COSTS_LABEL(84934),
		RECORD_KEEPING_COSTS_LABEL_CZERO(88090),
		
		SECTION_A_INTRODUCTION(84938), 
		SECTION_A_INTRODUCTION_DB(84946),
		SECTION_A_RK_CHAGRES_LABEL(84948),
		SECTION_A_DD_RK_CHARGES_PAYMENT_METHOD(84956), 
		SECTION_A_DD_RK_CHARGES_PAYMENT_METHOD_DB(84978),
		SECTION_A_ADJUSTMENT_RK_CHAGRES_LABEL(84950),  
		SECTION_A_BL_RK_CHARGES_PAYMENT_METHOD(84954),
		SECTION_A_PARTICIPANT_STATEMENT_FEE_LABEL(84952),
		SECTION_A_DD_PARTICIPANT_STATEMENT_FEE_PAYMENT_METHOD(84956), 
		SECTION_A_BL_PARTICIPANT_STATEMENT_FEE_PAYMENT_METHOD(84954),
		SECTION_A_RK_FEE_LABEL(84955),
		SECTION_A_RK_FEE_PAYMENT_METHOD(84956),
		SECTION_A_TOTAL_LABEL(84959),
		
		
		SECTION_B_INTRODUCTION(84961),
		SECTION_B_REVENUE_UNDERLYING_FUND_LABEL(84963),
		SECTION_B_REVENUE_UNDERLYING_FUND_PAYMENT_METHOD(84964),
		SECTION_B_REVENUE_JH_CHARGES_LABEL(84966),
		SECTION_B_REVENUE_JH_CHARGES_PAYMENT_METHOD(84980),
		SECTION_B_ADJUSTMENT_REVENUE_JH_CHAGRES_LABEL(84968),   
		SECTION_B_PRICE_CREDITS_LABEL(84970),  
		SECTION_B_TOTAL_LABEL(84972),
		
		
		REVENUE_NON_JH_CHARGES_LABEL(84974),
		REVENUE_NON_JH_CHARGES_PAYMENT_METHOD(84980),
		TOTAL_REVENUE_USED_LABEL(84976),
		
		//Class Zero Phase 2 Change
		DOLLAR_BASED_INTRO_LABEL(88060),
		DOLLAR_BASED_DESC_LABEL(88059),
		DOLLAR_BASED_DDPF_LABEL(88061),
		DOLLAR_BASED_DDPF_PAYMENT_METHOD(84956),
		DOLLAR_BASED_BLPF_LABEL(88061),
		DOLLAR_BASED_BLPF_PAYMENT_METHOD(84954),
		DOLLAR_BASED_DETLD_STMT_FEE_LABEL(88058),
		DOLLAR_BASED_DETLD_STMT_FEE_PAYMENT_METHOD(84956),
		DOLLAR_BASED_RECORD_KEEPING_CHARGES_LABEL(88057),
		DOLLAR_BASED_RECORD_KEEPING_CHARGES_PAYMENT_METHOD(84956),
		DOLLAR_BASED_ADMIN_FEE_LABEL(98998),
		DOLLAR_BASED_SMALL_PLAN_PPT_FEE_LABEL(98997),
		
		REPORT_IMP_INFO_N1_FOOTNOTE_KEY(85847),
		REPORT_IMP_INFO_N2_FOOTNOTE_KEY(85859),
		REPORT_IMP_INFO_N6_FOOTNOTE_KEY(77789), 
		REPORT_IMP_INFO_N7_FOOTNOTE_KEY(77806),   	
		REPORT_IMP_INFO_N7_FOOTNOTE_DB_KEY(77807),  
		REPORT_IMP_INFO_N10_FOOTNOTE_KEY(77793),        
		REPORT_IMP_INFO_N11_FOOTNOTE_KEY(77808),  
		REPORT_IMP_INFO_N11_FOOTNOTE_DB_KEY(85848),
		REPORT_IMP_INFO_N12_FOOTNOTE_KEY(77794),    
		REPORT_IMP_INFO_N13_FOOTNOTE_KEY(77795),                  
		REPORT_IMP_INFO_N13_FOOTNOTE_DB_KEY(77796), 
		REPORT_IMP_INFO_N14_FOOTNOTE_KEY(77798),   
		REPORT_IMP_INFO_N14_FOOTNOTE_DB_KEY(77799), 
		REPORT_IMP_INFO_N15_FOOTNOTE_KEY(77790),    
		REPORT_IMP_INFO_N19_FOOTNOTE_MSV_KEY(77804),
		REPORT_IMP_INFO_N19_FOOTNOTE_NMY_KEY(77804),
		REPORT_IMP_INFO_N20_FOOTNOTE_KEY(78445),    
		REPORT_IMP_INFO_N21_FOOTNOTE_KEY(80533), 
		REPORT_IMP_INFO_N23_FOOTNOTE_KEY(81729),
		REPORT_IMP_INFO_N24_FOOTNOTE_KEY(81730),
		REPORT_IMP_INFO_N25_FOOTNOTE_KEY(83615),
		REPORT_IMP_INFO_N10_FOOTNOTE_DB_KEY(88261),
		REPORT_IMP_INFO_N12_FOOTNOTE_DB_KEY(88263),
		REPORT_IMP_INFO_N24_FOOTNOTE_DB_KEY(88265),
		REPORT_IMP_INFO_N10_FOOTNOTE_NCZ_KEY(77793),
		REPORT_IMP_INFO_N12_FOOTNOTE_NCZ_KEY(77794),
		REPORT_IMP_INFO_N24_FOOTNOTE_NCZ_KEY(81730),
			
		REPORT_RECORD_KEEPING_CHARGES_BASE_ASSET_CHARGE_TEXT(79128),	
		REPORT_RECORD_KEEPING_CHARGES_ANNUALIZED_PPT_FEE_TEXT(78467),
		REPORT_RECORD_KEEPING_CHARGES_ANNUALIZED_PPT_FEE_TEXT_WITH_COMMA(79131),
		REPORT_RECORD_KEEPING_CHARGES_PINPOINT_CREDITS_FEE_TEXT(83647),
		REPORT_RECORD_KEEPING_CHARGES_PINPOINT_CREDITS_FEE_TEXT_WITH_COMMA(83645),
		REPORT_RECORD_KEEPING_FEE_N7_KEY(77810),
		REPORT_RECORD_KEEPING_FEE_N7_KEY_WITH_COMMA(77811),
		
		//Class Zero Foot notes for N7 and N11
		REPORT_IMP_INFO_N7_FOOTNOTE_KEY_CLASSZ_P2(88304),
		REPORT_RECORD_KEEPING_CHARGES_BASE_ASSET_CHARGE_TEXT_CLASSZ_P2(88312),
		REPORT_RECORD_KEEPING_CHARGES_ANNUALIZED_PPT_FEE_TEXT_WITH_COMMA_CLASSZ_P2(88316),
		REPORT_RECORD_KEEPING_CHARGES_ANNUALIZED_PPT_FEE_TEXT_CLASSZ_P2(88314),
		REPORT_RECORD_KEEPING_CHARGES_PINPOINT_CREDITS_FEE_TEXT_WITH_COMMA_CLASSZ_P2(88320),
		REPORT_RECORD_KEEPING_CHARGES_PINPOINT_CREDITS_FEE_TEXT_CLASSZ_P2(88318),
		
		REPORT_IMP_INFO_N11_FOOTNOTE_KEY_CLASSZ_P2(88302),
		REPORT_RECORD_KEEPING_CHARGES_BASE_ASSET_CHARGE_TEXT_CLASSZ_P2_N11(88306),
		REPORT_RECORD_KEEPING_CHARGES_ANNUALIZED_PPT_FEE_TEXT_WITH_COMMA_CLASSZ_P2_N11(88310),
		REPORT_RECORD_KEEPING_CHARGES_ANNUALIZED_PPT_FEE_TEXT_CLASSZ_P2_N11(88308);
		
		
				
		
		private int contentId;
	
		CmaKeys(int contentId){
			this.contentId = contentId;
		}
		
		public int getContentId(){
			return contentId;
		}
	}

}
